## _Numpy - Revisão_

_Data: 12/01/2023_             
_*Jocel Viana* - Cientista de dados_

In [1]:
# Importação da biblioteca
import numpy as np

In [7]:
# cria uma matriz unidimensional
mt = np.array([23, 34, 12, 67, 45, 23, 89, 45, 62])
print(mt)
print(type(mt)) # Verificar o tipo de dado

[23 34 12 67 45 23 89 45 62]
<class 'numpy.ndarray'>


In [16]:
# Cria um array com um tipo específico (float)
mt_float = np.array([23,45,23,75,67,45,32], dtype = np.float64)

print(mt_float)
print(type(mt_float))

# Cria um array de inteiros
mt_int = np.array([23,42,54,76,12,435,90], dtype = np.int32)
print(mt_int)
print(type(mt_int))

[23. 45. 23. 75. 67. 45. 32.]
<class 'numpy.ndarray'>
[ 23  42  54  76  12 435  90]
<class 'numpy.ndarray'>


#### _Mudar o tipo do array_

In [15]:
# Conversão de tipos
# De float para inteiro
mudei_tipo = mt_float.astype(np.int32)
print(f'De float para inteiro: {mudei_tipo}')

# de inteiro para float
mudei_tipo = mt_int.astype(np.float64)
print(f'De inteiro para float: {mudei_tipo}')

De float para inteiro: [23 45 23 75 67 45 32]
De inteiro para float: [ 23.  42.  54.  76.  12. 435.  90.]


#### _Array bidimensional_

In [18]:
# Cria uma matriz com 3 dimensões
mt2 = np.array([[12,43,56,34,56], [34,76,89,65,34], [56,89,90,76,98]])
mt2

array([[12, 43, 56, 34, 56],
       [34, 76, 89, 65, 34],
       [56, 89, 90, 76, 98]])

#### _Demais métodos numpy_

In [29]:
# Cria arrays tipificados
# Empty -> significa que não são inicializados, não que são vazios
print('===========Vazio============')
vazio = np.empty([3,3], dtype=int)
print(f'{vazio}')

print('\n===========Zeros============')

# Cria uma matriz 4x3 com valores zeros
zeros = np.zeros([4,3])
print(f'{zeros}')

print("\n===========Um's============")

# Cria uma matriz com valores 1's
um = np.ones([5,7])
print(f'{um}')

print('\n===========Diagonal============')

# Cria uma matriz com diagonal principal contendo valores 3 e os demias com zeros
diagonal = np.eye(8)
print(diagonal)

===========Vazio============
[[1399211056        109 1442387584]
 [       109 1442140592        109]
 [1442140848        109    6029312]]

===========Zeros============
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

===========Um's============
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]

===========Diagonal============
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


#### _Valores aleatórios_

In [36]:
# Valores aleatórios entre zeros e um
aleatorio1 = np.random.random([6])
print(aleatorio1)

print('=================================================')

# Aleatórios distribuição normal, contendo negativos
aleatorio2 = np.random.randn(10)
print(aleatorio2)

print('=================================================')

# Aleatórios 10 x 8
aleatorio3 = (10 * np.random.random((3, 4)))
print(aleatorio3)

[0.02128267 0.91978855 0.64164664 0.61388137 0.84310935 0.83408792]
[-2.0361973   0.03294941 -0.78093139  0.23901292  0.13841621 -0.65253896
 -0.3325824   0.19181105  1.12870011  0.49101859]
[[2.1679112  4.39767895 9.05129097 0.84003858]
 [2.36084085 8.22648494 7.46923404 5.42029864]
 [2.46380714 1.61460459 6.7803831  6.03066883]]


#### _Outras formas de gerar valores aleatórios_

In [45]:
# Uso de semente
gera = np.random.default_rng(18)
aleatorio4 = gera.random(3)
print(aleatorio4)

print('\n==================')

# Gerar inteiros
aleatorio5 = gera.integers(10, size=(3,5))
print(aleatorio5)

[0.39930577 0.71741468 0.28082333]

[[3 0 9 9 6]
 [5 5 6 7 5]
 [7 4 3 1 8]]


#### _Remove repetições_

In [46]:
# Método unique()
matriz = np.array([[2,2,4,3], [2,5,6,3], [5,7,2,2]])

unicos = np.unique(matriz)
print(unicos)

[2 3 4 5 6 7]


#### _Funções específicas_

In [48]:
# Matriz bidimensional
matriz2 = np.array([[23,54,65],[21,89,67], [78,90,245]])
print(matriz2)

# Busca um elemento específico
print(matriz2[2][1])

# Dimensões da matriz
print(matriz2.shape)

[[ 23  54  65]
 [ 21  89  67]
 [ 78  90 245]]
90
(3, 3)


#### _Funções matemáticas_

In [57]:
# Mostra o maior valor
print(matriz2.max())

# Menor valor
print(matriz2.min())

# Mostra a soma dos valores da matriz
print(matriz2.sum())

# Mostra a média
print(matriz2.mean())

# Mostra o desvio padrão
print(matriz2.std())

245
21
732
81.33333333333333
62.53354655258604


#### _Funções universais aplicadas a todos os elementos_


In [61]:
# Mostra o valor da raiz quadrada de todos os elementos
m = np.array([2,6,3,5,6])
print(np.sqrt(m))

# Mostra o valor do exponencial de todos os elementos
print(np.exp(m))

[1.41421356 2.44948974 1.73205081 2.23606798 2.44948974]
[  7.3890561  403.42879349  20.08553692 148.4131591  403.42879349]


#### _Extração de elementos_

In [65]:
# Cria o array
array = np.array([2,5,6,3,4])

# Mostra um elemento específico
print(array[2])

# Mostra o array da 2ª posição 
print(array[1])

# Mostra o array a partir do zero até dois elementos
print(array[0:2])

# Mostra a partir do antepenúltimo elemento até todo o restante
print(array[-3:])

6
5
[2 5]
[6 3 4]


#### _Extração de linhas e colunas_

In [80]:
# Cria um array
array2 = np.array([[3,6,4,5,3],[3,6,2,6,7],[45,76,45,32,45]])
print(array2)

print('\n==================')

# Primeira linha, todos os elementos
print(array2[0, :])
print('\n==================')

# Segunda linha
print(array2[1, :])
print('\n==================')

# Terceira linha
print(array2[2, :])
print('\n==================')

# Todas as linhas, primeira coluna
print(array2[:, 0])
print('\n==================')

# Todas as linhas, segunda coluna
print(array2[:, 1])
print('\n==================')

# Todas as linhas, terceira coluna
print(array2[:, 2])

[[ 3  6  4  5  3]
 [ 3  6  2  6  7]
 [45 76 45 32 45]]

[3 6 4 5 3]

[3 6 2 6 7]

[45 76 45 32 45]

[ 3  3 45]

[ 6  6 76]

[ 4  2 45]


#### _Operações com matrizes_

In [83]:
# Adição e multiplicação de matrizes
matriz3 = np.array([[2,5,3,4],[3,8,2,6]])
matriz4 = np.array([[3,7,1,7],[5,7,3,8]])
print('\n=======Soma======')
print(matriz3 + matriz4)

print('\n==Multiplicação==')
print(matriz3 * matriz4)


=======Soma======
[[ 5 12  4 11]
 [ 8 15  5 14]]

==Multiplicação==
[[ 6 35  3 28]
 [15 56  6 48]]


#### _Transposição, rearranjo de um conjunto de 15 elementos de 0 a 14_

In [88]:
# 3 linhas e 3 colunas
matriz5 = np.arange(15).reshape((3,5))
print(matriz5)

print('\n===Transposta===')
print(matriz5.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

===Transposta===
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


#### _Expressões lógicas_

In [94]:
# Usando where
# Cria uma matriz com valores aleatórios
v = np.random.randn(5,5)
print(v)


print('===================================')
# Cria uma matriz com valores booleanos baseados na matriz v
x = (v > 0)
print(x)

print('===================================')
# Cria uma matriz com valores -1 e 1 baseado no array x
z = np.where(x > 0, 1, -1)
print(z)

[[ 0.74613291  0.45852776 -0.83584512  1.88076869  0.67671513]
 [-1.92128267  0.62709973  0.81540068  0.21044206  1.99438766]
 [ 0.19011578  0.20719154  0.38607919  0.33182901  0.64464503]
 [-1.3487444  -0.19207165  0.23186223  0.11832242  0.19721279]
 [-0.71633599  0.25938747 -0.41051699 -0.03210332  0.79978213]]
[[ True  True False  True  True]
 [False  True  True  True  True]
 [ True  True  True  True  True]
 [False False  True  True  True]
 [False  True False False  True]]
[[ 1  1 -1  1  1]
 [-1  1  1  1  1]
 [ 1  1  1  1  1]
 [-1 -1  1  1  1]
 [-1  1 -1 -1  1]]
